version: "3.8"
services:
  server:
    build: ./server
    container_name: jenkinspipeline_server_c
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: jenkinspipeline_client_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkinspipeline_jenkins_c
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins

volumes:
  jenkins_data:
