export const theme = {
  primary: "#f6f5f2",
  secondary: "#1a8654",
  tertiary: "#0443a1",
  red: "#cf2e2e",
  hoverColor: "#1a86543a",
  dark: "#3c3f3d",
  light: "#FFFFEA",
  white: "#FFFFFF",
  fontSizemodalButtonMobile: "1.4rem",
  fontSizemodalButtonMobileTablet: "1.8rem",
  fontSizemodalButtonMobileDesktop: "2.2rem",
  fontSizemodalButtonMobileBigDesktop: "2.6rem",
  fontSizeformFieldItemsMobile: "1.4rem",
  fontSizeformFieldItemsTablet: "1.8rem",
  fontSizeformFieldItemsDesktop: "2rem",
  fontSizeformFieldItemsBigDesktop: "2.4rem",
  fontSizeButtonMobile: "0.8rem",
  fontSizeButtonMobileTablet: "1rem",
  fontSizeButtonMobileDesktop: "1.4rem",
  fontSizeButtonMobileBigDesktop: "1.8rem",
  fontSizeTitleMobile: "2.6rem",
  fontSizeTitleTablet: "3.2rem",
  fontSizeTitleDesktop: "3.8rem",
  fontSizeTitleBigDesktop: "4.4rem",
  tablet: "@media (min-width: 768px)",
  desktop: "@media (min-width: 1024px)",
  bigDesktop: "@media (min-width: 1280px)",
  huge: "@media (min-width: 1440px)",
};
